### ISSUE TITLE
Binary release not working

### ISSUE THREAD

**Issue by suntong** [mh-cbon/emd#27]
Hi, 

I just freshly installed emd from the emd deb repository, however, it is not working for me:

```
$ cat README.e.md 

## {{toc 5}}

## Usage

#### > {{cat "/tmp/test.go" | color "go"}}
```

Will give me, 

```
$ emd gen -out README.md
panic: gen failed: Generator failed: template: :9: function "toc" not defined

goroutine 1 [running]:
main.mustNotPanic(0x633300, 0xc420012840, 0xc4200a5f08, 0x1, 0x1)
        /home/travis/gopath/src/github.com/mh-cbon/emd/main.go:238 +0xc4
main.main()
        /home/travis/gopath/src/github.com/mh-cbon/emd/main.go:90 +0x591
```

If I remove `toc`, it will then give me, 

```
$ emd gen -out README.md
panic: gen failed: Generator failed: template: :1: function "cat" not defined

goroutine 1 [running]:
main.mustNotPanic(0x633300, 0xc4200127f0, 0xc420093f08, 0x1, 0x1)
        /home/travis/gopath/src/github.com/mh-cbon/emd/main.go:238 +0xc4
main.main()
        /home/travis/gopath/src/github.com/mh-cbon/emd/main.go:90 +0x591
```

Please verify. 

```
$ emd
emd - 0.0.2

Usage
  -help
        Show help
  -version
        Show version

Commands
        gen     Process an emd file.

$ apt-cache policy emd
emd:
  Installed: 0.0.2
  Candidate: 0.0.2
  Version table:
 *** 0.0.2 500
        500 https://mh-cbon.github.io/emd/apt/public all/contrib amd64 Packages
        100 /var/lib/dpkg/status

$ lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```

**Comment by suntong** [comment]
Installed again today, and works fine.
